from strategies.adxStrat import AdxStrategy
from strategies.aroonStrat import AroonStrategy
from strategies.atrBreakoutStrat import ATRBreakoutStrategy
from strategies.bollingerSqueeze import BollingerSqueezeStrategy
from strategies.cmoStrat import CMOStrategy
from strategies.donchianChannel import DonchianStrategy
from strategies.dpoStrat import DPOStrategy
from strategies.hmaCrossStrat import HMACrossStrategy
from strategies.ichimokuCloud import IchimokuCloudStrategy
from strategies.kamaStrat import KamaCrossStrategy
from strategies.keltnerChannel import KeltnerStrategy
from strategies.macdStrat.macdCross import MACDStrategy
from strategies.macdStrat.macdPullback import MACDPullbackStrategy
from strategies.macdStrat.macdSignalZero import MACDSignalZeroCrossStrategy
from strategies.macdStrat.macdSimplezero import MACDzeroCrossStrategy
from strategies.meanRev import MeanRevCrossStrategy
from strategies.momTrading import MomentumCrossStrategy
from strategies.movinAverage import MovinAverageCrossStrategy
from strategies.rsiStrat import RSICrossStrategy
from strategies.rviStrat import RVIStrategy
from strategies.sarStrat import SarCrossStrategy
from strategies.smaStrat import SmaCrossStrategy
from strategies.stochasticStrat import StochasticStrategy
from strategies.temaStrat import TEMACrossStrategy
from strategies.trixStrat import TRIXStrategy
from strategies.ultimateOscillator import UltimateOscStrategy
from strategies.vwapStrat import VWAPStrategy
from strategies.williamsStrat import WilliamsStrategy

STRATEGIES = {
    "ADX": AdxStrategy,
    "Aroon": AroonStrategy,
    "ATRBreakout": ATRBreakoutStrategy,
    "BollingerSqueeze": BollingerSqueezeStrategy,
    "CMO": CMOStrategy,
    "Donchian": DonchianStrategy,
    "DPO": DPOStrategy,
    "HMACross": HMACrossStrategy,
    "Ichimoku": IchimokuCloudStrategy,
    "Kama": KamaCrossStrategy,
    "Keltner": KeltnerStrategy,
    "MACD": MACDStrategy,
    "MACDPullback": MACDPullbackStrategy,
    "MACDSignalZero": MACDSignalZeroCrossStrategy,
    "MACDZero": MACDzeroCrossStrategy,
    "MeanReversion": MeanRevCrossStrategy,
    "Momentum": MomentumCrossStrategy,
    "MovingAverage": MovinAverageCrossStrategy,
    "RSI": RSICrossStrategy,
    "RVI": RVIStrategy,
    "SAR": SarCrossStrategy,
    "SMA": SmaCrossStrategy,
    "Stochastic": StochasticStrategy,
    "TEMA": TEMACrossStrategy,
    "TRIX": TRIXStrategy,
    "UltimateOscillator": UltimateOscStrategy,
    "VWAP": VWAPStrategy,
    "Williams": WilliamsStrategy,
}

STRATEGY_EXPLANATION_QUICK = {
    "ADX": "The Average Directional Index (ADX) measures the absolute strength of a trend, regardless of its direction. This strategy generates buy signals when a strong uptrend is confirmed by rising directional indicators.",
    "Aroon": "The Aroon indicator detects the start of new trends by measuring the time since the last high or low. A buy signal occurs when the upward momentum (Aroon Up) crosses above the downward momentum (Aroon Down).",
    "ATRBreakout": "This breakout strategy uses the Average True Range (ATR) to measure normal market volatility. It buys when the price breaks significantly above its normal fluctuation range – a sign of explosive, new momentum.",
    "BollingerSqueeze": "Based on Bollinger Bands. When the bands narrow extremely (the Squeeze), there is an unusual calm in the market. The strategy positions itself for the immediately following, strong price breakout to the upside.",
    "CMO": "The Chande Momentum Oscillator (CMO) calculates market momentum by directly comparing up and down days. Buy signals occur when the value crosses above the zero line from the oversold territory.",
    "Donchian": "The classic breakout strategy of the famous 'Turtle Traders'. It consistently buys when the price reaches a new high of the last X periods, breaking through the upper band of the Donchian Channel.",
    "DPO": "The Detrended Price Oscillator (DPO) mathematically removes long-term market trends to reveal pure, short-term price cycles. It buys at the isolated historical low points of these rhythms.",
    "HMACross": "Uses the Hull Moving Average (HMA), an extremely responsive and smoothed average that tracks the price with almost zero lag. It buys when the short-term HMA line crosses above the longer-term one.",
    "Ichimoku": "The Ichimoku Cloud is a comprehensive Japanese trend-following system. A buy signal is triggered when the price dynamically breaks out above the 'Cloud' (the resistance zone) and the uptrend is confirmed.",
    "Kama": "Kaufman's Adaptive Moving Average (KAMA) intelligently adapts to market speed: it remains flat in choppy, sideways markets and reacts quickly during true trends. This filters out noise and provides clean buy signals upon crossovers.",
    "Keltner": "Keltner Channels place dynamic bands around the price based on actual volatility (ATR). The strategy buys when the price has enough strength to dynamically break above the upper band.",
    "MACD": "The classic trend and momentum indicator. A buy signal occurs when the fast-reacting MACD line crosses above the slower signal line, indicating increasing upward momentum.",
    "MACDPullback": "Looks for established, strong uptrends in the MACD, but strategically waits for a short-term price retracement (pullback). It 'buys the dip' into temporary weakness before the main trend resumes.",
    "MACDSignalZero": "A very conservative and long-term MACD variant. The buy signal is only generated here when the slow signal line crosses above the central zero line, marking a stable, overarching trend change.",
    "MACDZero": "A classic signal generator for the transition from a bear to a bull market. It buys exactly when the main MACD line crosses the zero line into positive territory.",
    "MeanReversion": "The 'rubber band' strategy. Based on the statistical assumption that prices always return to their average after extreme movements. It buys counter-cyclically after strong, irrational sell-offs.",
    "Momentum": "Focuses on the pure acceleration of price movement. It buys when the current price significantly exceeds the price from X periods ago, indicating an intact and strong upward rally.",
    "MovingAverage": "The flexible standard among trend followers. It buys when a short-term moving price average breaks through a longer-term average from below to above.",
    "RSI": "The Relative Strength Index (RSI) identifies panic and euphoria. The strategy buys when the indicator value drops low (the market is 'oversold') and the price subsequently stabilizes and turns upwards.",
    "RVI": "The Relative Vigor Index (RVI) measures buyer conviction by comparing closing prices to opening prices. It buys when the momentum shifts into positive territory and a crossover signal occurs.",
    "SAR": "The Parabolic SAR places visual dots on the chart that follow the price like a trailing stop-loss. A fresh buy signal is generated when these dots flip from 'above the price' to the underside.",
    "SMA": "The absolute foundation of technical analysis. It buys at the famous 'Golden Cross', where a fast Simple Moving Average significantly crosses above a slow moving average.",
    "Stochastic": "This oscillator compares the current closing price with the price range of the recent past. It buys when the price breaks upwards out of the extremely oversold area (bear panic).",
    "TEMA": "The Triple Exponential Moving Average smooths the price three times. This almost completely eliminates the usual lag of moving average lines, allowing for extremely early and aggressive buy signals during trend changes.",
    "TRIX": "A momentum oscillator that ignores minor price fluctuations because it is based on a triple-smoothed price. A clean buy signal occurs when the TRIX line breaks through the zero line from bottom to top.",
    "UltimateOscillator": "Combines short-, medium-, and long-term momentum into a single value to avoid the usual false signals of standard oscillators. It typically buys during strong bullish divergences in the lower range.",
    "VWAP": "The Volume Weighted Average Price (VWAP) is one of the most important tools for institutional traders as it combines price and actual trading volume. A buy occurs when the price dynamically exceeds the volume-weighted average.",
    "Williams": "The Williams %R indicator measures momentum on a negative scale (0 to -100). The strategy looks for highly oversold markets and buys when the value dynamically breaks out upwards from the extreme negative range (below -80)."
}

STRATEGY_EXPLANATION_BUYING = {
    "ADX": "The ADX measures the pure trend strength. The direction is completely irrelevant in this context. The concept is built on purely quantitative foundations. A value above 25 confirms a strong trend. This is where the buy trigger of the strategy begins. The ADX must absolutely rise above 25. This shows the necessary strong market dynamics. Additionally, we need the two directional indicators. The +DI measures the strength of the buyers. The -DI measures the power of the sellers. The +DI must cross the -DI. This must clearly happen from below to above. Then the purchase is officially confirmed. The sell trigger protects the invested capital. It takes effect in the event of a looming trend reversal. If the +DI falls below the -DI, we sell immediately. The bears then take control once again. An alternative exit also exists in this strategy. If the ADX falls below 20, we also sell. The trend has then completely lost its structural strength.",
    "Aroon": "Aroon primarily measures the elapsed time. It is about the time passed since new highs or lows. The concept completely ignores the absolute price. There is an important Aroon Up line. There is also an Aroon Down line. The buy trigger is mechanically very clearly defined. The Aroon Up line must cross the Aroon Down line. This must absolutely happen from below. This shows extremely fresh bullish momentum. In addition, the Aroon Up value must rise above 50. This finally confirms the still young uptrend. The values often strive towards 100 in a trend. Then the prevailing trend is particularly strong. The sell trigger is just as mechanical with Aroon. It protects the trader from new downtrends. The Aroon Down line crosses the Aroon Up line upwards. That means absolute danger for the current trade. New lows are now being reached much faster again. The exit from the position occurs immediately. The capital is thus effectively and safely secured.",
    "ATRBreakout": "The ATR measures the true fluctuation range of the market. This is synonymous with the overall market volatility. The concept is based on strong price breakouts. We specifically look for extreme price movements. The buy trigger requires massive power from the bulls. The price must break an established resistance level. The candle must absolutely close above it. This alone is not enough for a signal. We additionally add a multiple of the ATR to the breakout. Mostly we use 1.5 times the current ATR for this. This filters out false breakouts extremely reliably. The bulls must show genuine and sustainable strength. After the purchase, the stop is set immediately. The sell trigger works very dynamically here. We use a so-called trailing stop mechanism. It is based on the highest high since entry. We rigorously subtract twice the ATR from this value. If the price ever falls below this, we sell. This gives the market enough room to breathe. At the same time, it effectively secures the accumulated profits.",
    "BollingerSqueeze": "Bollinger Bands excellently visualize the current market volatility. The concept methodically searches for absolute phases of calm. Before a huge storm, the market is usually quiet. The bands then contract extremely tightly together. This specific state is called the Bollinger Squeeze. The buy trigger waits exactly for this specific moment. The bandwidth reaches an absolute historical minimum. Then the price suddenly breaks out of the confinement. The current daily candle closes very high. It closes significantly far above the upper band. This is the final and explosive buying signal. The extreme expansion of volatility begins exactly now. We ride this new trend for as long as possible. The sell trigger limits our financial risk exposure. The trend will inevitably lose power at some point. The price then crosses the middle band downwards. This is the so-called 20-period simple moving average. A closing price below this triggers the immediate sale. The strong momentum is then officially broken. The position is closed completely without any hesitation.",
    "CMO": "The CMO measures pure and unfiltered market momentum. It calculates the sum of positive up days and negative down days. The concept is deeply mathematically structured. The indicator constantly swings around a central zero line. The buy trigger deliberately exploits extreme market conditions. First, the market falls sharply and in total panic. The CMO reaches the deeply oversold zone. The value drops significantly below minus 50. This means massive panic and capitulation in the market. However, we never buy directly during the free fall. We wait patiently for the reversal of market participants. The CMO crosses the zero line from below again. This action confirms the new and fresh uptrend. Now we are strategically perfectly positioned long. The sell trigger is the exact mirror image of this. The market inevitably becomes greedy and overbought over time. The CMO subsequently rises far above plus 50. Then the indicator dangerously turns back downwards. It crosses the zero line while falling rapidly. This is the unmistakable signal for immediate sale.",
    "Donchian": "Donchian Channels are visually and mathematically very simple. They stubbornly mark the highest and lowest historical prices. The concept is a classic and pure breakout system. It completely ignores any irrelevant market noise. The buy trigger is crystal clear for everyone to see. We look at the highs of the last 20 days. The price breaks the absolute highest high. In doing so, it forcefully pierces the upper Donchian band. This symbolizes massive and pure bullish market strength. A buy order is immediately placed into the market. The new trend is our best friend from now on. The sell trigger reacts deliberately a bit faster. We use a significantly shorter period for this action. Usually, we only look at the last 10 days here. The price falls below this specific lowest low. Then the lower band of the structure also breaks. That is the mathematically irreversible trend break. We do not hesitate for long in this moment. The position is closed immediately and consistently. This is exactly how strict and flawless trend following works.",
    "DPO": "The DPO effectively isolates very short-term market cycles. The macro trend noise is completely eliminated in the process. The concept is strictly cyclically based. The indicator swings harmoniously around a static zero line. The buy trigger seeks the ideal cycle trough. The DPO line falls extremely deep for this purpose. It reaches historical and significant low values there. The market is absolutely at the bottom cyclically speaking. Then the line aggressively and suddenly hooks upwards. It forcefully strives towards the zero line again. We buy exactly in this moment of the upswing. The new upward cycle has thus officially begun. The trade now runs synchronously with the market cycle. The sell trigger seeks the inevitable climax. The DPO line shoots very far upwards. It crosses the zero line massively and unchecked. An extreme cyclical peak is thereby reached. Then the line sharply hooks downwards again. The selling pressure now begins to rise noticeably. We sell immediately and secure our cycle profit.",
    "HMACross": "The HMA is a very special moving average. It eliminates almost the complete temporal delay. The concept is known in technical jargon as zero-lag. The strong smoothing is achieved through highly complex mathematics. We use two different HMA lines for the strategy. There is an extremely fast HMA with 9 periods. There is also a slower HMA with 21 periods. The buy trigger is a classic line crossover. The fast HMA crosses the slower HMA. This must absolutely happen from below to above. This indicates a lightning-fast and hard trend reversal. We buy directly upon this specific confirmation. The indicator is extremely sensitive at this level. The sell trigger is identical and logically structured. It protects us from very fast counter-movements. The fast HMA crosses hard downwards again. It falls significantly below the slow HMA. The exit from the trade occurs instantaneously. There is no room for errors or delays here. Pure speed is the absolutely central core of this system.",
    "Ichimoku": "The Ichimoku is a visually very complex system. It uses multiple factors for perfect confirmation. The concept seeks absolute clarity in the chart. There is a cloud as the centerpiece, the so-called Kumo. The buy trigger has three extremely strict rules. First, the price breaks significantly above the cloud. This shows the general and strong bull market. Second, the Tenkan-Sen must cross the Kijun-Sen. This intersection must be strictly directed upwards. Third, we check the important Chikou Span. This line is shifted exactly 26 periods into the past. It must strictly lie above the historical price at that time. We only buy if all three conditions are met. The system masterfully filters out false signals this way. The sell trigger, on the other hand, is very standardized. The price eventually falls below the Kijun-Sen. This is the very first and most important support. A complete drop below the cloud is fatal. At the latest then, the entire portfolio is sold. The capital is thus absolutely safe from long bear markets.",
    "Kama": "The KAMA dynamically adapts to market volatility. It reduces noise in difficult sideways phases. In strong trend phases, however, it reacts lightning-fast. The concept is based on purely adaptive mathematics. We often use different KAMA timeframes combined. The buy trigger always requires two clear signals. The short-term KAMA crosses the medium-term KAMA. This happens with momentum from below to above. Alternatively, the price itself crosses the main line. But the most important thing is the slope of the main KAMA. This slope must absolutely become positive and directed upwards. This irrevocably confirms the new uptrend. We now enter the long position with full risk. The sell trigger is unmistakable and hard. The trend is finished when the adaptive support breaks. The price falls below the moving main KAMA. The candle must close significantly below it. This is the final break of the bullish market structure. An immediate sale protects the previous profits. The adaptive system proves its true strength exactly here.",
    "Keltner": "Keltner Channels are mathematically based directly on the ATR. They show excellent and dynamic breakout zones. The concept tirelessly searches for extreme strength. Normal price movements always remain obediently within the channels. The buy trigger therefore requires an absolute exception. We look for a strongly bullish and massive candle. This must close completely outside the channel. It must lie above the upper band with its body. This proves abnormal buyer strength in the entire market. Nobody voluntarily sells at these prices anymore. We buy directly after this significant closing price. The bullish breakout is thus formally and clearly confirmed. The sell trigger later brings us back to reality. The price almost always returns into the channel. But that alone is absolutely no reason to sell. We only sell at the dynamic center line. This line is usually a 20-period EMA. If the price falls below it, the uptrend is dead. The bulls have then completely used up their power. We therefore close the trade absolutely immediately.",
    "MACD": "The MACD is a world-famous classic momentum indicator. It is based on the convergence and divergence of averages. The concept uses exponential moving averages for this. There is a very fast primary MACD line. There is also a slower smoothed signal line. The buy trigger is the world's most famous buying signal. The fast line crosses the slower signal line. This happens dynamically from below to above. The short-term momentum immediately turns in favor of the buyers. The buy signal is extremely mechanical and crystal clear. This often happens while still deep in negative territory. That points to a very early and profitable trend reversal. We open our long position exactly at this signal. The sell trigger is the exact mirror image of the entry. The enormous dynamics of the uptrend eventually weaken. The fast MACD line subsequently falls again. It crosses the slow signal line downwards. The sellers take over the scepter in the market again. The generated sell signal is strictly implemented. Emotions have absolutely no place with this proven indicator.",
    "MACDPullback": "This strategy intelligently seeks the perfect reentry. We trade exclusively in strongly intact uptrends. The concept is classic and safe pullback trading. The price must absolutely lie above the 200-SMA. This confirms the overarching global macro trend. The buy trigger intensively uses the MACD histogram. The market usually corrects briefly and sharply downwards. The histogram thereby falls deep below the zero line. The generated bars become red and highly negative. Then the momentum suddenly turns upwards again. The histogram becomes positive and bright green again. The bearish pullback is thus highly officially ended. We immediately reenter the main trend. The sell trigger protects against real trend changes. The histogram could unexpectedly fall below zero again. That would be an alarming sign of enormous weakness. Alternatively, the price falls below the saving 50-SMA. This short-term average serves as our emergency brake. If one of these signals occurs, we sell radically. The reentry strategy is thus safely concluded.",
    "MACDSignalZero": "This is a very deliberate and conservative strategy. It avoids many false and unnecessary entries. The concept focuses purely on the central zero line. We look exclusively at the slow signal line. This line is heavily smoothed by the EMA. The buy trigger requires extreme patience from the trader. The signal line slowly approaches the zero line. Then it forcefully crosses it from below to above. This marks the transition into continuously positive territory. A fundamental and long-lasting bull market is now confirmed. The signal comes late, but it is very safe. We invest our entire capital in the trade. The sell trigger follows the exact same calm logic. The bear market usually announces itself very slowly. The smoothed signal line gradually sinks again. It eventually crosses back below the zero line. The market is now firmly in negative territory. We liquidate our positions immediately and completely. Large losses due to deep crashes are thus effectively avoided. Security and capital preservation always come first with this approach.",
    "MACDZero": "This is a much wilder and more aggressive method. It aims at enormously fast trend reversals. The concept also uses the critical zero line. Here, however, we only consider the primary MACD line. This line is much faster and significantly more nervous. The buy trigger reacts extremely early here. The primary line breaks brutally through the zero line. It rises from below directly into the positive area. The momentum abruptly flips to massively bullish. We buy directly at this clear breakout. We are positioned far ahead of the broad masses. The risk is indeed higher, but so is the potential profit. The sell trigger is absolutely consistent and hard. The emerging trend can quickly turn out to be a false breakout. The primary line then immediately loses altitude again. It falls mercilessly back below the zero line. The momentum is deep red and bearish again. We realize the impending loss or small profit immediately. Holding on to the position for a long time is absolutely forbidden here. Speed is the all-important factor in this setup.",
    "MeanReversion": "Markets almost always return to their historical average. The concept trades very counter-cyclically directly against the trend. We look for extreme panic-like exaggerations. Mathematically, we often use the so-called Z-score for this. The buy trigger is firmly based on these extremes. The Z-score falls far below the value of minus two. Alternatively, the normal RSI falls deep below 20. Both signals indicate pure and irrational market panic. However, we never buy blindly into the free fall. The first daily candle must absolutely close higher than it opened. This is our absolutely indispensable reversal confirmation. The bulls thus show a first real sign of life again. Now the counter-cyclical entry is absolutely perfect. The sell trigger is simultaneously our targeted profit goal. We do not wait for a month-long bull market here. The price converges back to its mathematical mean. This mean is usually the simple 20-period SMA. As soon as the price touches this SMA, we sell immediately. The quick pullback profit is thus safely booked. The trade is successful and quickly finished.",
    "Momentum": "Momentum measures the pure and raw price speed. It compares the current price with the deep past. The concept visualizes the acceleration of the overall market. The values swing completely freely around a zero line. The buy trigger is extremely focused on dynamics. The momentum line must cross the zero line hard. This must absolutely happen from below to above. The current price is now higher than exactly N periods ago. The upward speed has officially become positive. We step immediately into this wildly accelerating market. The bulls have built up extreme and sustainable pressure. As long as the value remains positive, we hold the position. The sell trigger meticulously monitors the braking effect. The market often suddenly loses its momentum. The momentum line then crosses below the zero line. The speed becomes mathematically negative in the same moment. The current price drops below the old reference price. The buyers have completely and entirely given up. The position is closed immediately and mercilessly. Only absolute speed generates returns here in the end.",
    "MovingAverage": "This is the absolute and undisputed classic in trading. The concept is based on very simple average values. It filters out the daily market noise extremely perfectly. We always use two different time horizons for this. The buy trigger is a simple and clear crossover. A very short average crosses a slightly longer one. For example, the 20-SMA crosses the well-known 50-SMA. This crossing must strictly occur from below to above. The short-term sentiment is now much more bullish than the long-term. The buy signal is extremely objective, rigid, and flawless. One invests immediately upon the final confirmation of the candle. The young trend now has a very solid foundation. The sell trigger is exactly as mechanical in reverse. The short-term mood of the participants deteriorates again. The short SMA crosses the long SMA downwards again. The bears now clearly dominate the short-term action. A fresh downtrend has just firmly established itself. The ripcord is pulled immediately by selling. All profits are thereby very consistently protected. Simplicity is definitely the true key to success here.",
    "RSI": "The RSI is a globally extremely dominant indicator. It precisely measures overbought and oversold conditions. The concept is based on relative internal price strength. By default, exactly 14 periods are calculated for this. The buy trigger ruthlessly exploits temporary market weakness. The RSI value falls deeply and quickly below 30. The entire market is now massively oversold. An immediate blind purchase would be far too risky, however. We wait patiently for the real return of the buyers. The RSI forcefully crosses back above the 30 line. The buy signal is now completely and safely confirmed. The massive downward pressure is mathematically completely over. The sell trigger protects us from the emerging greed. In a strong uptrend, the market will inevitably overheat. The RSI rises steeply and extremely above the 70 mark. All market participants are extremely euphoric at this point. Then the RSI suddenly breaks below 70 again. The euphoria fades immediately, new sellers step in hard. We sell immediately and take our profits. The counter-cyclical oscillator concept has worked perfectly here.",
    "RVI": "The RVI analyzes the pure intraday buying power in detail. It directly compares the closing price with the opening price. The concept is extremely focused on true daily strength. We have a main line and a signal line in the system. The buy trigger looks for extreme and hidden turning points. Both lines are deep in the negative area. The bears were extremely dominant intraday for a long time. Now the RVI line crosses its signal line upwards. The bulls now manage to close candles high again. The internal buying power turns massively into the positive. This buy signal immediately leads to a lucrative long trade. The confidence in the new intraday pressure is enormously high. The sell trigger, however, saves us from bitter losses. The trend eventually reaches the positive extreme territory. The bulls suddenly lose their usual intraday dominance. The RVI line crosses the signal line hard downwards. The daily candles increasingly close very close to the opening again. This is an absolutely unmistakable sign of massive weakness. We end the risky trade instantly. The strict intraday logic dictates this extremely rapid exit.",
    "SAR": "The Parabolic SAR is a visually fascinating tool. The concept is a strictly dynamic trend-following stop. The visualized dots visualize the parabolic acceleration. The indicator visually lies either above or below the price. The buy trigger is extremely visual and idiot-proof simple. The price is in a steep downward trend. The SAR dots lie oppressively like a lid over the candles. Now the price suddenly rises strongly and dynamically. It touches and breaks the SAR dot directly above it. In the exact next period, the mathematical magic happens. The dot completely flips downwards below the price. The new upward trend has now officially started. We aggressively buy into this new trend. The sell trigger is the exact and consistent opposite. The dots now lie protectively right under the candles. The price, however, suddenly corrects strongly downwards. It touches the formulated stop dot clearly from above. The SAR immediately flips protectively over the price again. The upward trend has turned and we sell immediately. This asymmetrical system secures profits extremely effectively.",
    "SMA": "The SMA delivers by far the strongest macro signals. The concept is extremely long-term and solidly oriented. We use the most important moving averages in the financial world. These are the 50-day and the mighty 200-day SMA. The buy trigger has a very famous English name. This lucrative phenomenon is called the Golden Cross. The 50-day SMA rises massively and persistently. It crosses the 200-day SMA dominantly from below. This marks the indisputable start of real, huge bull markets. Institutional investors buy worldwide on exactly this signal. We also invest massively in the broad market. Absolute patience is extremely important with this strategy. The sell trigger is just as prominently and fearfully named. One fears the so-called deadly Death Cross. The massive upward trend collapses massively after many months. The 50-day SMA crosses the 200-SMA downwards. A massive, long-term, and destructive bear market now threatens. We sell our complete stock holdings absolutely immediately. Consistent capital preservation is the very first top priority here. Historically speaking, this method is extremely profitable.",
    "Stochastic": "The Stochastic is an oscillator perfect for ranging markets. The concept evaluates the current price against the historical range. There is a very fast %K line and a slow %D line. The buy trigger takes place deep down in the basement. Both lines fall far below the critical 20 mark. The bears dominate the market absolutely and mercilessly here. Then the fast %K crosses the slow %D. This must mandatorily and clearly occur from below to above. An subsequent strong breakout above 20 is ideal. The buy signal is thus perfectly and finally validated. The counter-movement of the bulls has now unleashed its full power. We open our long position completely without any hesitation. The sell trigger is triggered at a very dizzying height. The market climbs deep into the extreme overbought zone. Both lines are trading extremely high above the 80 mark. The buyers have now completely spent their powder. The fast %K line crosses wildly below the %D line. This negative crossover in the extreme area is absolutely deadly. The price will inevitably plummet sharply shortly. The unconditional sale saves our hard-earned profits.",
    "TEMA": "The TEMA is an ingenious, triple-smoothed average. The concept eliminates practically every tiny bit of market noise. It reacts extremely aggressively to price changes despite the smoothing. Absolute trend following is truly taken to the extreme here. The buy trigger is incredibly simple but enormously highly efficient. The closing price shoots up extremely rapidly. It crosses the TEMA line strongly from below to above. Alternatively, two TEMA lines cross like a fast crossover. The momentum is immediately and absolutely bullish afterwards. There is hardly any measurable temporal delay at entry. We buy immediately upon the first signal confirmation. The established trend is now stubbornly ridden. The sell trigger, in return, tolerates no weakness whatsoever. The price must mandatorily hold stubbornly at the top. If the closing price falls cleanly back below the TEMA line. Then the trend is mathematically immediately and irrevocably dead. There is no buffer or generous tolerance zone here. The exit occurs uncompromisingly and extremely quickly. False alarms are very rare due to the strong smoothing. A truly excellent system for very dynamic markets.",
    "TRIX": "The TRIX is an excellent percentage rate of change indicator. The concept uses a complex, triple-smoothed EMA. It filters out unimportant zigzag movements absolutely perfectly. The indicator possesses an all-important central zero line. The buy trigger offers two truly excellent options. The integrated signal line provides a very early signal. The TRIX line crosses its signal line directly from below. That is an extremely aggressive and highly profitable early entry. The safer and slightly later signal uses the zero line. TRIX crosses the zero line directly into the positive area. That is the absolute and final trend confirmation. A massive purchase is executed upon one of the signals. The sell trigger takes effect immediately upon any loss of momentum. The strongly smoothed TRIX line visibly drops off. It crosses below its own, slower signal line. This warns massively of an acutely impending trend reversal. The hard and uncompromising exit signal is the zero line. If TRIX falls below it, the momentum is officially negative. We sell the large position completely without further ado. The strategy scores enormously with its extreme mathematical smoothness.",
    "UltimateOscillator": "This brilliant oscillator directly combines three different timeframes. The concept weighs short, medium, and long-term pressure. Because of this, many common and expensive false signals are avoided. The buy trigger is firmly based on a bullish divergence. The price falls massively to an even lower low. The oscillator, however, does not confirm this massive price drop. It stays above 30 and forms a much higher low. The sellers lose power invisibly and slowly here. However, that alone is definitely not enough for a purchase. The oscillator must break above its last intermediate peak. Only this specific breakout triggers the final buy signal. The highly complex calculation makes this signal extremely strong. The sell trigger protects the trader from trend exhaustion. Enormous danger threatens in the extremely overbought zone above 70. If a bearish divergence forms here, we sell immediately. The price continues to rise, but the indicator is already dropping. Alternatively, the absolute value falls cleanly below 50. The bulls have then completely surrendered control. The exit is mandatory and uncompromisingly required. The highly complex system pays off in massive profits.",
    "VWAP": "The VWAP is the absolute darling of all large institutions. The concept weights the price directly based on the volume. It shows the true, undeniable average price of the big players. The complex calculation is restarted every single day. The buy trigger strictly requires an enormous trading volume. The price must dynamically break through the magic VWAP line. This must happen hard from below to above. At the same time, the traded volume must rise extremely sharply. A breakout without strong volume is completely worthless and false. The high volume confirms the gigantic institutional buying interest. We swim directly with the big fish with this setup. We open our huge position immediately at the VWAP. The sell trigger is strictly tied to the final closing price. The ongoing trend will often only briefly test the VWAP. A short intraday dip is absolutely tolerable and normal. However, if the price closes below the important VWAP line. Then the market sentiment completely flips into the extreme negative. The institutions are no longer defending this important level. We must pull our ripcord immediately and uncompromisingly. We sell everything and end this risky VWAP play.",
    "Williams": "Williams %R measures momentum on a strongly inverted scale. Crazily enough, the concept ranges from zero to minus one hundred. It is an extremely fast and highly volatile indicator. The buy trigger lurks very deep in the extreme extreme zone. The value must fall extremely far below minus 80. The entire market is then absolutely and mercilessly oversold. We wait patiently for the aggressive, bullish pivot point. The indicator turns upwards extremely sharply there. It forcefully crosses the minus 80 mark from below. This quick snapback triggers the immediate and hard purchase. The bulls have suddenly and unexpectedly taken over the market. The subsequent recovery is usually extremely rapid and profitable. The sell trigger only becomes relevant again in the overbought zone. The value rises rapidly and unchecked above minus 20. The pure greed in the market reaches its absolute blind peak. The indicator suddenly loses all of its upward momentum. It crosses the minus 20 mark quickly back downwards. The rapid and profitable recovery rally is officially over. We secure our extremely fast profits immediately. The highly counter-cyclical approach has perfectly fulfilled its task."
}


def get_strategy(name="SMA"):
    return STRATEGIES.get(name)

def strategy_is_valid(strategy):
    return strategy in STRATEGIES

def get_strategy_explanation_quick(strategy):
    return STRATEGY_EXPLANATION_QUICK[strategy]

def get_strategy_explanation_buying(strategy):
    return STRATEGY_EXPLANATION_BUYING[strategy]